[package]
name = "winvd"
version = "0.0.15"
authors = ["Jari Otto Oskari Pennanen"]
license = "MIT"
edition = "2018"
description = "Provides functions for accessing Windows 10 virtual desktop API"
readme = "README.md"
homepage = "https://github.com/ciantic/VirtualDesktopAccessor/tree/rust/"
repository = "https://github.com/ciantic/VirtualDesktopAccessor/tree/rust/"

[dependencies]
com = "0.2.0"
once_cell = "1.4.0"
crossbeam-channel = { version = "0.4.2" }

[lib]
name = "winvd"
path = "src/lib.rs"

[features]
debug = []

[package.metadata.docs.rs]
default-target = "x86_64-pc-windows-msvc"

[workspace]
members = [
    "testbin",
]